### ISSUE TITLE
renv.lock requires CohortDiagnostics version 3.0.0 which has not been released

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SkeletonCohortDiagnosticsStudy#7]
https://github.com/OHDSI/SkeletonCohortDiagnosticsStudy/blob/0572d2dd4d43a431c0e1f065cf729ff00a8096f9/renv.lock#L442

When I run renv::restore() I get the error

Error: failed to retrieve 'https://api.github.com/repos/ohdsi/CohortDiagnostics/tarball/v3.0.0' [error code 22]
In addition: Warning message:
curl: (22) The requested URL returned error: 404 

I think this is because the most current version of CohortDiagnostics is 2.2.4 

https://github.com/OHDSI/CohortDiagnostics/blob/3836704a674e68964dfa6ef13f8777bcea60780d/DESCRIPTION#L4

**Comment by gowthamrao** [comment]
not good :)
